Repository BioSchemas/bioschemas.github.io, pull requests merged in 2019-06, with the labels that each got.

#200 Release ChemicalSubstance 0.2-DRAFT
  _devSpecs/ChemicalSubstance.html
Labels: enhancement

#201 Update profile explanation
  index.html
  specifications/drafts.html
  specifications/index.html
  types/drafts.html
  types/index.html
Labels: enhancement, prior: high

#210 Correct cardinality of dataset property on DataCatalog
  _devSpecs/DataCatalog.html
Labels: bug, prior: high
