Repository BioSchemas/bioschemas.github.io, pull requests merged in 2020-10, with the labels that each got.

#327 Redirect governance to Governance repo
  community/governance.html
Labels: bug, enhancement

#326 Added Chunlei to the Tools role
  community/index.html
Labels: enhancement

#328 Update use cases link
  _profiles/Journal/0.1-DRAFT-2019_11_21.html
  _profiles/PublicationIssue/0.1-DRAFT-2019_02_08.html
  _profiles/PublicationVolume/0.1-DRAFT-2019_02_15.html
  _profiles/ScholarlyArticle/0.1-DRAFT-2019_03_15.html
  _profiles/SemanticAnnotation/0.1-DRAFT-2019_11_19.html
  _useCases/ScholarlyPublications.html
Labels: use case

#331 Update latest presentation
  index.html
  publications/index.html
Labels: enhancement

#334 Remove test files
  _profiles/Dataset/0.4-DRAFT.html
  _profiles/Dataset/0.5-RELEASE.html
Labels: bug, prior: high

#337 Add COVID-19 data portal to live deploy list
  _liveDeploys/liveDeploy.md
Labels: Live Deploy

#336 Update community call date
  index.html
Labels: enhancement, prior: high

#330 Add iPPI-DB to list of live deploys
  _liveDeploys/liveDeploy.md
Labels: Live Deploy
