Repository BioSchemas/bioschemas.github.io, pull requests merged in 2021-04, with the labels that each got.

#380 Move tutorials to the Bioschemas website
  _includes/head.html
  _includes/mobile_navbar.html
  _includes/navbar.html
  _includes/tutorialNavigation.html
  _layouts/tutorial.html
  tutorials/howto/howto_add_github.md
  tutorials/howto/howto_add_markup.md
  tutorials/howto/howto_check_deploy.md
  tutorials/howto/howto_right_profile.md
  tutorials/index.md
  tutorials/markup_examples.md
  tutorials/what_why_bioschemas.md
  tutorials/what_why_schema.md
Labels: training

#387 Fix biogicalRole typo on some of the released types
  _profiles/BioSample/0.1-DRAFT-2019_11_12.html
  _types/BioChemEntity/0.7-RELEASE-2019_06_19.html
  _types/BioSample/0.1-RELEASE-2019_06_19.html
  _types/ChemicalSubstance/0.2-RELEASE-2019_06_19.html
  _types/Gene/0.2-RELEASE-2019_06_19.html
  _types/MolecularEntity/0.2-RELEASE-2019_06_23.html
  _types/Protein/0.2-RELEASE-2019_06_19.html
Labels: bug, type

#394 Add E-UK hackathon
  _meetings/2021-04_E-UKHackathon.md
Labels: Meetings

#389 Attempt to fix Issues 494
  _includes/navbar.html
Labels: bug, prior: high, training

#391 Remove empty section
  tutorials/howto/howto_add_markup.md
Labels: bug, training

#390 Update BMUSE service URL
  tutorials/howto/howto_check_deploy.md
Labels: training

#381 List Bioschemas Training Portal in live deploys
  _liveDeploys/liveDeploy.md
Labels: Live Deploy, training

#393 Add Google Rich Results Test example
  tutorials/images/google_rich.png
Labels: training

#399 BridgeDb Data now conform Dataset 0.4-DRAFT
  _liveDeploys/liveDeploy.md
Labels: Live Deploy, enhancement

#396 Minor corrections to text of Schema.org What and Why tutorial
  tutorials/what_why_schema.md
Labels: training

#392 Add Google Rich Results Test
  tutorials/howto/howto_check_deploy.md
Labels: training

#400 Update call date
  index.html
Labels: Meetings, prior: high
