Repository BioSchemas/bioschemas.github.io, pull requests merged in 2021-11, with the labels that each got.

#468 ComputationalTool 1.0-RELEASE
  _data/live_deployments.json
  _data/profile_versions.yaml
  pages/_posts/2021-11-02-ComputationalTool-Profile-1.0-RELEASE.md
  pages/_profiles/ComputationalTool/1.0-RELEASE.html
Labels: profile

#478 Create Pull Release template for profile release
  .github/PULL_REQUEST_TEMPLATE/profile-release-PR-template.md
Labels: enhancement

#481 Add details of RDA18 and ELIXIR Data/InterOp meetings
  pages/_meetings/2021-11_ELIXIR-DataInterOp.md
  pages/_meetings/2021-11_RDA18.md
Labels: Meetings

#447 Add more detail to adding markup tutorial
  _includes/image.html
  pages/_tutorials/howto/howto_add_markup.md
  pages/_tutorials/images/brca_gene_html.png
  pages/_tutorials/images/brca_gene_summary.png
  pages/_tutorials/images/code_on_head.png
Labels: training

#485 Add Bgee to live deploys
  _data/live_deployments.json
  pages/_posts/2021-11-08-Bgee-Deployment.md
Labels: Live Deploy

#487 Add metanetx to live deploy list
  _data/live_deployments.json
  pages/_posts/2021-11-11-metanetx-deployment.md
Labels: Live Deploy

#489 Fix broken link
  pages/_posts/2021-05-28-Disease-Profile-0.1-DRAFT.md
Labels: bug

#483 Some guidance for when to select MolecularEntity and ChemicalSubstance
  pages/_tutorials/howto/howto_right_profile.md
Labels: training

#493 Update next community call date
  index.html
Labels: Meetings
