Repository BioSchemas/bioschemas.github.io, pull requests merged in 2021-05, with the labels that each got.

#402 Update howto_right_profile.md
  tutorials/howto/howto_right_profile.md
Labels: training

#342 Added mention of ELIXIR scientific programme
  _includes/navbar.html
  community/related.md
  index.html
Labels: enhancement

#409 Add Stian to tools group
  _groups/Tools.md
Labels: people

#404 Fixed image URL
  tutorials/howto/howto_check_deploy.md
Labels: bug, training

#403 Update Live Deploy page to use data in JSON format
  .github/workflows/validate-live-deploys.yml
  _data/live_deployments.json
  _data/live_deployments_schema.json
  _liveDeploys/liveDeploy.md
  liveDeploys/elixir.html
  liveDeploys/index.html
Labels: Live Deploy, enhancement
