Repository BioSchemas/bioschemas.github.io, pull requests merged in 2021-02, with the labels that each got.

#364 Added Quentin to biodiversity champions list
  community/champions.html
Labels: enhancement, people

#247 Added STRING-db to live deploys of Proteins
  _liveDeploys/liveDeploy.md
Labels: Live Deploy

#362 Show the latest release number on live deploys headers
  liveDeploys/index.html
Labels: Live Deploy, enhancement

#365 Linkfix
  _includes/profile_start.html
  _includes/specification_table.html
  _profiles/ComputationalWorkflow/0.5-DRAFT-2020_07_21.html
  _types/ComputationalWorkflow/0.1-DRAFT-2020_07_21.html
Labels: bug, type

#363 Tutorial on checking deployed markup
  tutorials/howto/howto_add_github.md
  tutorials/howto/howto_check_deploy.md
  tutorials/images/bioschemasValidator.png
  tutorials/images/google_struct.png
  tutorials/images/inspect-markup.png
  tutorials/index.md
Labels: training

#370 Update next meeting date
  index.html
Labels: Meetings

#375 Add Matus Kalas
  _groups/Tools.md
  _people/MatusKalas.md
Labels: people
