Repository BioSchemas/bioschemas.github.io, pull requests merged in 2022-03, with the labels that each got.

#518 Update next call date
  index.html
Labels: Meetings

#512 Rare Disease Tutorial
  _includes/navbar.html
  pages/_tutorials/community/rd.md
  pages/_tutorials/community_tutorials.md
Labels: training

#507 Community tutorials
  _config.yml
  _includes/navbar.html
  _includes/tutorial-navigation.html
  assets/css/_code-highlight.scss
  assets/css/_community.scss
  assets/css/main.scss
  pages/_community/index.html
  pages/_tutorials/community/idp.md
  pages/_tutorials/community/index.md
  pages/_tutorials/community/plant.md
  pages/_tutorials/community/rd.md
  pages/_tutorials/howto/howto_add_github.md
  pages/_tutorials/howto/howto_add_markup.md
  pages/_tutorials/howto/howto_check_deploy.md
  pages/_tutorials/howto/howto_create_new_profile.md
  pages/_tutorials/howto/howto_new_profile_version.md
  pages/_tutorials/howto/howto_right_profile.md
  pages/_tutorials/images/bioschemasFields.png
  pages/_tutorials/images/profileInfo.png
  pages/_tutorials/images/propertiesInitial.png
  pages/_tutorials/images/propertiesMarginality.png
  pages/_tutorials/index.md
  pages/_tutorials/markup_examples.md
  pages/_tutorials/what_why_bioschemas.md
  pages/_tutorials/what_why_schema.md
Labels: training

#525 Updated the metadata and selected an example without space encodings in the URL
  _data/live_deployments.json
Labels: enhancement

#517 Add news item about deployment
  pages/_news/2022-01-26-PathVisio-Deployment.md
Labels: News

#526 FAIR-checker news
  pages/_news/2022-03-23-FAIR-checker-release.md
Labels: News

#524 Add example deployments of TrainingMaterial
  _data/live_deployments.json
  pages/_news/2022-03-22-TrainingMaterials-Deployments.md
Labels: Live Deploy

#528 News item about TrainingMaterial 1.0 RFC
  pages/_news/2022-03-25-TrainingMaterial-1.0_RFC.md
Labels: News

#530 Update next call date
  index.html
Labels: Meetings
